name = "ExampleIDW"
uuid = "5cb377e6-c40b-4784-bf7d-004dc88db9dc"
authors = ["Jaqueline Teixeira Diamantino"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
